### ISSUE TITLE
SourceID lost in sFlow->Netflow conversion

### ISSUE THREAD

**Issue by simosilakka** [sflow/sflowtool#14]
When capturing sFlow to stdout I can see that the packet has a sourceId field that tells me the interface the packet was sent from. For Comware this field has a value of 0:4 for interface GigabitEthernet1/0/4. When I convert the flow to Netflow v9, SourceId is always 0. In Netflow v5 there is a EngineId field, not sure if this is for the same use, but this is always 0 also.

**Comment by sflow** [comment]
The sFlow sourceId indicates the sFlow data-source (observation-point).
The EngineId is equivalent to the sFlow "agentSubId" and should always be 0 for this export.

So the field you should examine -- the one that maps to the NetFlow input ifindex -- is the field that sflowtool prints as "inputPort".  If your Comware switch is not populating the inputPort field in sFlow packet-samples then that is something to ask them about.

(You may sometimes see egress-samples with inputPort==0 and ingress-samples with outputPort==0,  but it's much better if the sFlow agent can populate both of these with every sample.)
