### ISSUE TITLE
unknown address type

### ISSUE THREAD

**Issue by szhong12** [sflow/sflowtool#15]
use sflowtool and receive the following warnings repeatedly:
unknown address type = 3
caught exception: 1
unknown address type = 0
caught exception: 1
unknown address type = 0
caught exception: 1
unknown address type = 0
caught exception: 1
unknown address type = 3
caught exception: 1
unknown address type = 25972
caught exception: 1
unknown address type = 25972
caught exception: 1

**Comment by sflow** [comment]
Sounds like something went wrong with the XDR encode/decode.   I suggest you capture a binary trace of the input sFlow that triggers this error and post it here as an attachment.  Along with any relevant make+model info about the source.

For example,  the capture command to get 100 packets might be:
sudo tcpdump -s0 -w sflow.pcap -c 100 udp port 6343

And to confirm that it triggers the error:
sflowtool -r sflow.pcap

If that is not an option for one reason or another,  then I suggest you compile from sources with DEBUG set (./boot.sh && ./configure CFLAGS="-g -DDEBUG" && make) and then run with gdb.  That way the error will trigger abort() and you can examine the stack etc.

Neil
