### ISSUE TITLE
sflowtool Ipv6 error

### ISSUE THREAD

**Issue by cpecus** [sflow/sflowtool#18]
When I execute the command sflowtool +4 -p 6343 -l for listen in ipv4 and ipv6 I have this error:
"v4 bind() failed, port = 6343 : Address already in use" and I can only see ipV4 directions.

**Comment by cpecus** [comment]
And when execute ./sflowtool -6 -p 6343 -l   I see only ipv4 directions.

**Comment by sflow** [comment]
This looks like it might be on Linux. The default on Linux is to open an IPv6 socket on the port (same as "-6" option).  On Linux an unbound IPv6 socket will accept all IPv4 and IPv6 packets,  so if tcpdump or wireshark can see IPv6 packets arriving that do not appear in sflowtool then it's more likely to be an issue with the host firewall config (ip6tables) or reverse path filtering.

Sorry it's not more clear what is going on here.
