### ISSUE TITLE
IPv4 and IPv6 socket bind error

### ISSUE THREAD

**Issue by RamyVeng** [sflow/sflowtool#19]
Hi Team,

The SFLOW v5 packets are being forwarded from Source port number 6343 to Destination port number 2055. (FYI - 2055 is the port number configured in my server)
I am facing the below issues when running the sflowtool commands to pretty print the data,

Issue1# IPv6
./sflowtool -p 2055 -l
v6 socket() creation failed, Address family not supported by protocol

I saw few options to run IPv4 alone. So tried the below scenario,
Issue2# IPv4
./sflowtool -4 -p 2055 -l
v4 bind() failed, port = 2055 : Address already in use
unable to open UDP read socket

Does the tool runs on the same port number(2055 in my case) it is listening ?
If so is there a way I can change the config so that the process can run on a port number and listen on another port number ?

Could you please help me out in fixing these above 2 issues?

Thanks.

**Comment by SlightOmission** [comment]
Are you sure 2055 isn't already being used somewhere?  What does `lsof -Pni udp:2055` display when sflowtool is *not* running?

**Comment by sflow** [comment]
To listen on port 6343 and forward to port 2055 on the same IPv4-only host,  you probably want something more like this:

sflowtool -4 -p 6343 -f 127.0.0.1/2055
