### ISSUE TITLE
Problem with redirection - getaddrinfo() failed: Name or service not known

### ISSUE THREAD

**Issue by Sonique** [sflow/sflowtool#20]
Tried on mac, docker debian and debian servers. v3.41d

```
➜  ~  sflowtool -p 6345 -f hostname.company.com/6434
getaddrinfo() failed: Name or service not known

```

same with netwlow redirection
```
➜  ~  sflowtool -p 6345 -c localhost -d 6377
netflow collector hostname lookup failed
```

**Comment by devicenull** [comment]
We've hit this as well, and have resorted to just hardcoding IP addresses.

**Comment by devicenull** [comment]
This turns out to be a single character fix:
````
diff --git a/src_clean/src/sflowtool.c b/src_clean/src/sflowtool.c
index a46aeb2..b209549 100644
--- a/src_clean/src/sflowtool.c
+++ b/src_clean/src/sflowtool.c
@@ -4753,7 +4753,7 @@ static int addForwardingTarget(char *hostandport)
     return NO;
   }

-  if(parseOrResolveAddress(hoststr, (struct sockaddr *)&sa, &tgtIP, 0, 1) == NO) {
+  if(parseOrResolveAddress(hoststr, (struct sockaddr *)&sa, &tgtIP, 0, 0) == NO) {
     return NO;
   }
   switch(tgtIP.type) {
````

**Comment by sflow** [comment]
Without the "AI_NUMERICHOST" hint, my understanding is that getaddrinfo() may try a DNS lookup even if the address offered is obviously numeric, and waiting for a DNS response may take as long as a minute.   For low-level infrastructure tools like this it doesn't make sense to risk that kind of delay,  so using only numeric addresses is encouraged.  Nevertheless, I added a "-D" option that you can include if you know what you are doing and you really need to specify a netflow collector or forwarding target by name.

So this now works:

sflowtool -D -f localhost/7777

but you should really do this:

sflowtool -f 127.0.0.1/7777
