### ISSUE TITLE
Strange ARP packet handling

### ISSUE THREAD

**Issue by jasperem** [sflow/sflowtool#22]
Hi,

I try to convert saved sFlow samples to line by line CSV format using `sflowtool -l -r file.pcap` and get lines as described below for ARP packets.

```
49835 0.000000 192.168.2.3	 172.168.3.4	   TCP 1522 80 → 28449 [ACK] Seq=1 Ack=1 Win=118 Len=1448 TSval=123456 TSecr=123456
49836 0.000000 12:34:56:78:9a:bc 12:34:56:78:9a:be ARP 68   192.168.7.1 is at 12:34:56:78:9a:bc[Packet size limited during capture]
```

was converted to:

```
FLOW,192.168.5.1,12345,12346,abcdef123456,abcdef123457,0x0800,1,1,192.168.2.3,172.168.3.4,17,0x00,254,80,28449,0x10,1522,1500,1024
FLOW,192.168.5.1,12345,12346,12cdef123456,12cdef123457,0x0806,1,1,192.168.2.3,172.168.3.4,17,0x00,254,80,28449,0x10,68,46,1024
```

Why are the fields that are not used in the ARP packet filled with the contents of the previous packet?

Could you fix this behaviour?

**Comment by sflow** [comment]
Thanks.  Some of the decoded fields are cached, but they were not being reset properly for the next sample.  Note that ARP fields will now appear like this:

FLOW,10.0.0.202,2,5,f20a6acbfcb4,ffffffffffff,0x0806,0,0,-,-,0,0x00,0,0,0,0x00,64,60,400

(Those "-" strings for the IP addresses might cause problems if you were not expecting them.  They should probably be empty-strings,  but sflowtool has printed "-" for undefined IP addresses for a long time so I should probably leave that alone.)

Any use of the -l output option should probably be replaced with either the -j or -L <field1,field2,...,fieldN> options anyway.  I would encourage you to investigate those if you haven't already.

**Comment by jasperem** [comment]
Thanks a lot for the quick reaction. I have already found a solution for me :)
