### ISSUE TITLE
Getting error to parse JSON

### ISSUE THREAD

**Issue by anumercian** [sflow/sflowtool#28]
I used this script that I got online to parse the JSON output:
 #!/usr/bin/env python

import subprocess
from json import loads

p = subprocess.Popen(
  ['/usr/local/bin/sflowtool','-j'],
  stdout=subprocess.PIPE,
  stderr=subprocess.STDOUT
)
lines = iter(p.stdout.readline,'')
for line in lines:
  print line
  datagram = loads(line)
  localtime = datagram["localtime"]
  samples = datagram["samples"]
  for sample in samples:
    sampleType = sample["sampleType"]
    elements = sample["elements"]
    if sampleType == "FLOWSAMPLE":
      for element in elements:
        tag = element["flowBlock_tag"]
        if tag == "0:1":
          try:
            src = element["srcIP"]
            dst = element["dstIP"]
            pktsize = element["sampledPacketSize"]
            print "%s %s %s %s" % (localtime,src,dst,pktsize)
          except KeyError:
            pass

**And I get this error:**
Traceback (most recent call last):
  File "./flow.py", line 14, in <module>
    datagram = loads(line)
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 1 column 264 (char 263)

When I looked through the JSON, the JSON format is missing a ",":
"datagramSourceIP":"104.3.28.3","datagramSize":"716","unixSecondsUTC":"1563314035","localtime":"2019-07-16T21:53:55+0000","datagramVersion":"5","agentSubId":"0","agent":"15.11.20.2","packetSequenceNo":"1812216","sysUpTime":"1122908000",**"samplesInPacket":"4""samples":**[{"sampleType_tag":"0:1"

**Comment by anumercian** [comment]
I think I found the issue in the code sflowtool.c file.

A comma is needed in these instances to make the JSON a valid one:
1. Before starting a "samples": keyword and appending a comma to it
2. Before starting an "elements": keyword and appending a comma to it
3. If there are more than 1 samples, appending a "comma" in between
4. If there are more than 1 elements, appending a "comma" in between

I am relatively novice in coding C, so will try to fix the bug and push a pull request.

**Comment by sflow** [comment]
Fixed and released 5.04.  Thanks!
