### ISSUE TITLE
Wrong sampling interval value setting when converting from sFlow to Netflow with -s option

### ISSUE THREAD

**Issue by NickGudov** [sflow/sflowtool#29]
Hello

When -s option is set sflowtool must set same sampling interval in netflow header as in sflow.
In fact, sampling interval is always 0.
Looks like in code below "&" operator must be replaced by "|".

https://github.com/sflow/sflowtool/blob/6c2963b1c1b75b384ba6c9ce27e6272fdc11dc25/src/sflowtool.c#L2078

**Comment by sflow** [comment]
Yes.  Well spotted.  I have checked in the change.  OK for your name to be added to the AUTHORS file?  I also fixed a problem with the corresponding field in the NetFlow v9 export.  It's better to use v9 if you can, if only because it allows 32-bit ifIndex numbers.

**Comment by NickGudov** [comment]
> OK for your name to be added to the AUTHORS file?

Ok
