### ISSUE TITLE
About skipping block on decodeIPV6 function.

### ISSUE THREAD

**Issue by ng-labo** [sflow/sflowtool#31]
I'd like to suggest that a bit of the correction about skipping IP6HeaderExtension on decodeIPV6 function.
 After this code block, the variable 'ptr' shall point to the Layer 4 header. I don't understand what '-2' means on 'skip = optionLen - 2;'. This would cause the wrong pointer for next header. I think the adjustment does not be needed.

 I've checked the case of "fragment ". In this case, just the first packet of fragments would be effective for decodeIPLayer4() next in samples. With correction, it would be decoded expectedly.

```
    /* skip over some common header extensions...
       http://searchnetworking.techtarget.com/originalContent/0,289142,sid7_gci870277,00.html */
    while(nextHeader == 0 ||  /* hop */
	  nextHeader == 43 || /* routing */
	  nextHeader == 44 || /* fragment */
	  /* nextHeader == 50 => encryption - don't bother coz we'll not be able to read any further */
	  nextHeader == 51 || /* auth */
	  nextHeader == 60) { /* destination options */
      uint32_t optionLen, skip;
      sf_logf_U32(sample, "IP6HeaderExtension", nextHeader);
      nextHeader = ptr[0];
      optionLen = 8 * (ptr[1] + 1);  /* second byte gives option len in 8-byte chunks, not counting first 8 */
      skip = optionLen - 2;
      ptr += skip;
      if(ptr > end) return; /* ran off the end of the header */
    }
```

**Comment by sflow** [comment]
Yes,  you are right.  I'll fix that.  Thank you!
