### ISSUE TITLE
Help to analyze packets with sflowtool

### ISSUE THREAD

**Issue by SomeAkk** [sflow/sflowtool#33]
Hello!

I try to analyze raw packets with **sflowtool** which i found in wild. That packets was googled in Wireshark pcaps format, pcap file named `sflow.cap`.  `sflow.cap` normally decoded to human view by Wireshark and by that i suppose that packets from `sflow.cap` is not broken. But when i try to analyze that packets with **sflowtool** i had some errors.

Let's look at 1 packet in `sflow.cap`:
`0000000500000001ac152311000000010000019f673dd71000000001000000020000006c000021250000040c0000000100000001000000580000040c000000060000000005f5e100000000010000000300000000018c2ccc00009b83000290160001f6730000000000000000000000000000000000533dc10000a0b700002187000008d7000000000000000000000000`

In Whireshark it's ok:
![ws](https://user-images.githubusercontent.com/57045709/101333208-661f4d80-3887-11eb-9cc9-7647b26e49f4.png)

I downloaded sflowtool and started it to listen 6343 port:
```
test@srv-test-01:~$ sudo sflowtool -p 6343
```

Then, I try to send raw packets in hex (shown below) and in binary (not shown) formats:
```
echo -n "0000000500000001ac152311000000010000019f673dd71000000001000000020000006c000021250000040c0000000100000001000000580000040c000000060000000005f5e100000000010000000300000000018c2ccc00009b83000290160001f6730000000000000000000000000000000000533dc10000a0b700002187000008d7000000000000000000000000" >/dev/udp/localhost/6343
```

In sflowtool that packet generate error:
```
startDatagram =================================
datagramSourceIP 0.0.0.1
datagramSize 288
unixSecondsUTC 1607333061
localtime 2020-12-07T04:24:21-0500
datagramVersion 808464432
unexpected datagram version number
 (source IP = 0.0.0.1)
30-30-30-30-<*>-30-30-30-35-30-30-30-30-30-30-30-31
61-63-31-35-32-33-31-31-30-30-30-30-30-30-30-31
30-30-30-30-30-31-39-66-36-37-33-64-64-37-31-30
30-30-30-30-30-30-30-31-30-30-30-30-30-30-30-32
30-30-30-30-30-30-36-63-30-30-30-30-32-31-32-35
30-30-30-30-30-34-30-63-30-30-30-30-30-30-30-31
30-30-30-30-30-30-30-31-30-30-30-30-30-30-35-38
30-30-30-30-30-34-30-63-30-30-30-30-30-30-30-36
30-30-30-30-30-30-30-30-30-35-66-35-65-31-30-30
30-30-30-30-30-30-30-31-30-30-30-30-30-30-30-33
30-30-30-30-30-30-30-30-30-31-38-63-32-63-63-63
30-30-30-30-39-62-38-33-30-30-30-32-39-30-31-36
30-30-30-31-66-36-37-33-30-30-30-30-30-30-30-30
30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30
30-30-30-30-30-30-30-30-30-30-35-33-33-64-63-31
30-30-30-30-61-30-62-37-30-30-30-30-32-31-38-37
30-30-30-30-30-38-64-37-30-30-30-30-30-30-30-30
30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30
caught exception: 2
endDatagram   =================================
```

Founded by me sflow.cap example: 
[sflow.cap.zip](https://github.com/sflow/sflowtool/files/5651768/sflow.cap.zip)

1. So what i do wrong?
2. How can i test another sflow packets which in binary/hex format?

**Comment by sflow** [comment]
Looks like you are close.  Just need a hex-to-binary conversion step using something like netcat or xxd:
https://unix.stackexchange.com/questions/82561/convert-a-hex-string-to-binary-and-send-with-netcat

**Comment by SomeAkk** [comment]
@sflow looks like it is. I thought that just hex would be enough for that purpose - my mistake. Thx for help! 
Now will be looking in packets which capture. 

If **sflowtool** not give enough data about packet, with reason "skipping unknown sample", does it mean that packet incompatible with sFlow v5?

I got strange packet from Cisco Nexus 3172T switch (also in [docs](https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus3000/sw/system_mgmt/7_x/b_Cisco_Nexus_3000_Series_NX-OS_System_Management_Configuration_Guide_7x/b_Cisco_Nexus_3000_Series_NX-OS_System_Management_Configuration_Guide_7x_chapter_010110.html) sad that it can send data only by sFlow):

```
echo -n "0000000500000001efbfbdefbfbd01efbfbd00000064006e727eefbfbdefbfbdefbfbdefbfbd0000000600000003000000efbfbd00247defbfbd000000001600001e000013efbfbdc8b64cefbfbd0000533c000000001600001e00000000160000" | xxd -r -p | nc -4u -q1 localhost 6343
```
sflowtool output:
```
startDatagram =================================
datagramSourceIP 127.0.0.1
datagramSize 97
unixSecondsUTC 1607371072
localtime 2020-12-07T14:57:52-0500
datagramVersion 5
agentSubId 3216835055
agent 239.191.189.239
packetSequenceNo 3216834560
sysUpTime 6553710
samplesInPacket 1920921535
startSample ----------------------
sampleType_tag 777979:4029
skipping unknown sample: 777979:4029 len=-272646673
caught exception: 1
endDatagram   =================================
```

Also if try to look at packet and i broken up at `number of samples field`, try to use [that doc](https://sflow.org/developers/diagrams/sFlowV5Datagram.pdf):
```
packet:
0000000500000001efbfbdefbfbd01efbfbd00000064006e727eefbfbdefbfbdefbfbdefbfbd0000000600000003000000efbfbd00247defbfbd000000001600001e000013efbfbdc8b64cefbfbd0000533c000000001600001e00000000160000

decoded:
00000005 - version
00000001 - ip4 type
efbfbdef - ip
bfbd01ef - agent sub id
bfbd0000 - datagram number
0064006e - switch uptime in ms
727eefbf - n samples in datagram wtf?!
bdefbfbd - ?
efbfbdef - ?
bfbd0000 - ?
00060000 - ?
00030000 - ?
...
```

**Comment by sflow** [comment]
I haven't studied what the xxd and netcat are doing here, but this seems very unlikely to be what the switch is really sending.  If you have is a pcap file with sFlow packets from the switch then I suggest you use this option:

sflowtool -r sflow.pcap

**Comment by SomeAkk** [comment]
> I haven't studied what the xxd and netcat are doing here, but this seems very unlikely to be what the switch is really sending. If you have is a pcap file with sFlow packets from the switch then I suggest you use this option:
> 
> sflowtool -r sflow.pcap

got another pcap from another device, tool works good, thx for help - another questions will go to cisco and their "maybe sflow format"
