### ISSUE TITLE
Release source tarball

### ISSUE THREAD

**Issue by nunotexbsd** [sflow/sflowtool#39]
Hello,

Could this project provide a release source tarball, e.g, [sflowtool-5.0.7.tar.gz](https://github.com/sflow/sflowtool/releases/download/v5.0.7/sflowtool-5.0.7.tar.gz) to be included toguether with Release Assets?

This have the advantage to download source code from a fixed tarball instead of an auto-generated one: https://github.com/sflow/sflowtool/archive/refs/tags/v5.07.tar.gz.

Since I'm maintaining FreeBSD CopyQ [port](https://www.freshports.org/net/sflowtool/), instead of using github account name/project to get auto-generated source tarball, I could simply use a simple command to fetch from a static url:

from:

```
PORTNAME=       sflowtool
DISTVERSIONPREFIX=      v
DISTVERSION=    5.0.7

USE_GITHUB=     yes
GH_ACCOUNT=     sflow
GH_PROJECT=     sflowtool

distinfo:
SHA256 (sflow-sflowtool-v5.07_GH0.tar.gz) = ###
SIZE (sflow-sflowtool-v5.07_GH0.tar.gz) = ###
```

to:

```
PORTNAME=       sflowtool
DISTVERSION=    5.0.7
MASTER_SITES= https://github.com/sflow/sflowtool/releases/download/v${DISTVERSION}/

distinfo:
SHA256 (sflowtool-5.0.7.tar.gz) = ###
SIZE (sflowtool-5.0.7.tar.gz) = ###
```

IMO, all packaging systems that needs fetching and compiling from source will beneficit with this static tarball.

Example: https://github.com/jordansissel/xdotool/releases

Thanks,

Nuno Eduardo Teixeira
[eduardo@FreeBSD.org](mailto:eduardo@FreeBSD.org)

**Comment by sflow** [comment]
Do you want the named tarball file to be exactly the same as the <tag>.tar.gz that is in the release assets now?
https://github.com/sflow/sflowtool/archive/refs/tags/v5.07.tar.gz

Or do you mean the sflowtool-5.07.tar.gz file that you get when you run this sequence of commands:
git clone https://github.com/sflow/sflowtool
cd sflowtool
./boot
./configure
make dist

**Comment by nunotexbsd** [comment]
Well thats the diference of [auto-generated tarball ](https://github.com/sflow/sflowtool/archive/refs/tags/v5.07.tar.gz) and a fixed static one like in https://github.com/jordansissel/xdotool/releases.
The main advantage is that port builders like FreeBSD ports framework could access a static tarball without github access (account and project name).

**Comment by sflow** [comment]
I put the tarball generated by "make dist" into the 6.02 release assets:  sflowtool-6.02.tar.gz.  Please let me know if this is what you were looking for.  (And sorry this took so long).

**Comment by nunotexbsd** [comment]
Comparing git fetch versus tarball, I found some differences:

sflow_xdr.h is missing from tarball (critical, don't build):
`Only in git/sflowtool-6.02/src: sflow_xdr.h`

```
Only in tarball/sflowtool-6.02: INSTALL
Only in tarball/sflowtool-6.02: Makefile.in
Only in git/sflowtool-6.02: README.md
Only in tarball/sflowtool-6.02: aclocal.m4
Only in git/sflowtool-6.02: boot.sh
Only in tarball/sflowtool-6.02: compile
Only in tarball/sflowtool-6.02: config.guess
Only in tarball/sflowtool-6.02: config.sub
Only in tarball/sflowtool-6.02: configure
Only in tarball/sflowtool-6.02: depcomp
Only in tarball/sflowtool-6.02: install-sh
Only in tarball/sflowtool-6.02: missing
Only in tarball/sflowtool-6.02/src: Makefile.in
```
Could it be fixed?

Thanks!

**Comment by sflow** [comment]
I believe it is fixed now:  'make dist' (in master branch) now includes sflow_xdr.h in the tarball.  I replaced the tarball asset in the 6.02 release so it should work now.

The other differences are because from the raw repo-clone you start with "./boot.sh",  while from the 'make dist' tarball you go straight to "./configure".

Let me know if I need to change anything else.

**Comment by nunotexbsd** [comment]
Tarball is good and update committed ( https://cgit.freebsd.org/ports/commit/?id=abeafb07e548861c4477df576e757a2965620358 )

Thanks!
