### ISSUE TITLE
sflowtool cannot obtain sflow data.

### ISSUE THREAD

**Issue by lzy350593418** [sflow/sflowtool#40]
Why can Sflow-RT and Tcpdump obtain sflow data, but sflowtool cannot obtain sflow data?

**Comment by lzy350593418** [comment]
After the command is used, the command is stuck. sflow packet information is not printed.However, Sflow-RT listening to 6343 will get sflow data. Tell Me Why, please?

**Comment by lzy350593418** [comment]
Sorry, I left the firewall on.....

**Comment by sflow** [comment]
We have all done that!  Closing issue.
