### ISSUE TITLE
output port number for the same interface,

### ISSUE THREAD

**Issue by richie-tt** [sflow/sflowtool#7]
Hello,
First of all I want to say that, You are making good job with sflowtool, my company use that great tool as proxy to store sflow information in Logstash according to that guide (https://whiskeyalpharomeo.com/2015/06/13/logstash-and-sflow/)

now more about problem:
so recently I checked the logs and I noticed when the packet is coming from the same physical interface
for example: let say when some packet arrived from eth1 vlan1 and after routing process it was send back to the same interfaces eth1 but others vlan2, the sflowtool gives me correct information about incoming interfaces but outgoing interfaces is 0

Sample:

```
....
dstIP       10.9.9.13
dstPort         42684
in_vlan         199
inputPort       573
inputPortName       Trk12
out_vlan        210
outputPort      0
outPortName
srcIP       10.10.10.16
srcPort         6379
tcpFlags        0x10
#traffic3       148KB
....
```

 In sample you can see that packet from IP 10.9.9.13, vlan 199 from interfaces 573 (HP port numbering) was routed and sent to IP 10.10.10.16,  vlan 210 and to the same interfaces 573(after my investigation) but sflowtool gave me 0 for outgoing interfaces .

If you want I can send you more samples, the problem occurs only for packets which back to the same interface.

**Comment by sflow** [comment]
Hi,

If the packet is being sent to more than one output ifIndex then it's normal to see 0 here meaning "unknown" -- or to see a code such as 0x80000002 meaning "sent to 2 interfaces".

To comment I would need to know which sFlow agent is generating the packet samples.  Open vSwitch?  hsflowd?

P.S. Thanks for the link!  Interesting.  Dumping asciified sFlow into ELK seems brute-force to me.   You could probably get two orders of magnitude more scalability if you inserted something like sFlow-RT to extract data post de-dup/roll-up and feed ELK from there.   Easy to consume sFlow counters that way too.

**Comment by richie-tt** [comment]
Hi,
Thank You for answer, I have to say sFlow-RT looks very nice, but unfortunately I noticed there the same problems, so I begin to suspect that this can be a problem of BUG from IOS, but I want to confirm that on another software.

Agent is Core switch HP 3800 and it use sflow  (Datagram Version Support  : 5).

For outputPort I just make the workaround and when the number is 0 for output, then the Logstash just copy value from input port, according to my investigation this rule works when outputPort is 0.

Unfortunately today I noticed that inputPort also sometimes gave 0 or 1073741823 as number of interface port and always it gave inputVlan as -1 in such cases.
I didn't find and rule here, when I compared to output data.

From following sample You see that, in the third column (inputPort infomarion) sometimes shows 0, 1073741823

`FLOW,10.1.11.1,563,592,5475d0283adb,001a4a744923,0x0800,55,55,217.85.70.192,10.50.5.12,6,0x00,56,50271,443,0x10,74,52,256
FLOW,10.1.11.1,579,0,001a4a16016a,10604bb76125,0x0800,213,214,10.2.13.27,10.2.14.25,6,0x08,64,39470,3306,0x18,453,431,256
FLOW,10.1.11.1,1073741823,571,001a4a16015a,9c8e992433d0,0x0800,116,116,10.1.16.24,10.1.16.27,6,0x00,64,60286,9211,0x10,1522,1500,256
FLOW,10.1.11.1,1073741823,577,001a4a16016d,001a4a16016b,0x0800,214,214,10.2.14.25,10.2.14.24,6,0x08,64,3306,57489,0x18,398,376,256
FLOW,10.1.11.1,0,592,10604bb76125,001a4a744937,0x0800,-1,113,10.1.12.244,10.1.13.13,6,0x00,63,52060,4444,0x04,68,46,256
FLOW,10.1.11.1,0,574,10604bb76125,001a4a7449a1,0x0800,-1,217,10.2.14.18,10.2.17.17,6,0x00,63,27017,43893,0x10,1522,1500,256
FLOW,10.1.11.1,592,0,001a4a744924,10604bb76125,0x0800,218,217,10.2.18.242,10.2.17.18,6,0x00,64,53105,81,0x18,669,647,256
FLOW,10.1.11.1,1073741823,571,001a4a160159,9c8e992433d0,0x0800,116,116,10.1.16.23,10.1.16.27,6,0x00,64,36729,9212,0x10,1522,1500,256
FLOW,10.1.11.1,0,579,10604bb76125,001a4a16017b,0x0800,-1,213,10.2.12.244,10.2.13.31,6,0x00,63,34981,8000,0x10,74,52,256
FLOW,10.1.11.1,573,592,001a4a744968,001a4a74498b,0x0800,214,214,10.2.14.13,10.2.14.15,6,0x00,64,11210,47217,0x10,1522,1500,256
FLOW,10.1.11.1,1073741823,571,001a4a16015a,9c8e992433d0,0x0800,116,116,10.1.16.24,10.1.16.27,6,0x00,64,60286,9211,0x10,1522,1500,256
FLOW,10.1.11.1,0,573,10604bb76125,001a4a744927,0x0800,-1,214,10.2.13.13,10.2.14.16,6,0x00,63,48241,6379,0x18,119,97,256
CNTR,10.1.11.1,74,6,1000000000,1,3,732066500,2239457,549056,258888,0,0,0,1411924949,1566715,8762568,557697,0,0,0
FLOW,10.1.11.1,592,0,001a4a744930,10604bb76125,0x0800,112,114,10.1.12.244,10.1.14.24,6,0x00,64,54646,5672,0x10,74,52,256
FLOW,10.1.11.1,578,571,001a4a160159,9c8e992433d0,0x0800,116,116,10.1.16.23,10.1.16.27,6,0x00,64,60290,9211,0x10,1522,1500,256
FLOW,10.1.11.1,1073741823,563,001a4a744923,5475d0283adb,0x0800,55,55,10.50.5.12,80.134.1.46,6,0x00,64,443,46081,0x10,1442,1420,256
FLOW,10.1.11.1,563,592,5475d0283adb,001a4a744923,0x0800,55,55,191.101.109.190,10.50.5.12,6,0x00,55,41751,443,0x10,74,52,256
FLOW,10.1.11.1,574,592,001a4a744956,001a4a744955,0x0800,114,114,10.1.14.10,10.1.14.16,6,0x00,64,33660,6379,0x10,74,52,256
FLOW,10.1.11.1,1073741823,578,9c8e992433d0,001a4a16015a,0x0800,116,116,10.1.16.27,10.1.16.24,6,0x00,64,9211,60286,0x10,86,64,256
FLOW,10.1.11.1,571,578,9c8e992433d0,001a4a160159,0x0800,116,116,10.1.16.27,10.1.16.23,6,0x00,64,9212,36729,0x10,74,52,256
FLOW,10.1.11.1,571,578,9c8e992433d0,001a4a16015a,0x0800,116,116,10.1.16.27,10.1.16.24,6,0x00,64,9212,49061,0x10,1522,1500,256
FLOW,10.1.11.1,573,0,001a4a744927,10604bb76125,0x0800,214,213,10.2.14.16,10.2.13.13,6,0x00,64,6379,48322,0x18,85,63,256
FLOW,10.1.11.1,579,592,001a4a160175,10604bb76125,0x0800,113,112,10.1.13.30,10.1.12.241,6,0x08,64,60195,3306,0x18,215,193,256
FLOW,10.1.11.1,0,573,10604bb76125,001a4a744927,0x0800,-1,214,10.2.13.24,10.2.14.16,6,0x00,63,54853,6379,0x18,113,91,256
FLOW,10.1.11.1,0,592,10604bb76125,001a4a744933,0x0800,-1,114,10.1.12.244,10.1.14.24,6,0x00,63,56508,5672,0x10,74,52,256
FLOW,10.1.11.1,1073741823,571,001a4a16015a,9c8e992433d0,0x0800,116,116,10.1.16.24,10.1.16.27,6,0x00,64,49061,9212,0x10,1522,1500,256
FLOW,10.1.11.1,578,571,001a4a16015a,9c8e992433d0,0x0800,116,116,10.1.16.24,10.1.16.27,6,0x00,64,60286,9211,0x10,1522,1500,256
FLOW,10.1.11.1,1073741823,571,001a4a160159,9c8e992433d0,0x0800,116,116,10.1.16.23,10.1.16.27,6,0x00,64,36729,9212,0x10,1522,1500,256
FLOW,10.1.11.1,578,571,001a4a160159,9c8e992433d0,0x0800,116,116,10.1.16.23,10.1.16.27,6,0x00,64,36729,9212,0x10,1522,1500,256
FLOW,10.1.11.1,1073741823,571,001a4a16015a,9c8e992433d0,0x0800,116,116,10.1.16.24,10.1.16.27,6,0x00,64,60286,9211,0x10,1522,1500,256
FLOW,10.1.11.1,0,574,10604bb76125,001a4a7449a1,0x0800,-1,217,10.2.18.242,10.2.17.17,6,0x00,63,57338,81,0x10,74,52,256
FLOW,10.1.11.1,563,592,5475d0283adb,001a4a744923,0x0800,55,55,78.110.27.65,10.50.5.26,6,0x00,61,41644,443,0x18,767,745,256
FLOW,10.1.11.1,1073741823,563,001a4a744923,5475d0283adb,0x0800,55,55,10.50.5.12,213.162.145.191,6,0x00,64,443,54188,0x10,1442,1420,256
FLOW,10.1.11.1,0,573,10604bb76125,001a4a744996,0x0800,-1,213,10.2.14.16,10.2.13.21,6,0x00,63,6379,39818,0x18,78,56,256
FLOW,10.1.11.1,1073741823,571,001a4a16015a,9c8e992433d0,0x0800,116,116,10.1.16.24,10.1.16.27,6,0x00,64,49061,9212,0x10,1522,1500,256
FLOW,10.1.11.1,571,578,9c8e992433d0,001a4a16015a,0x0800,116,116,10.1.16.27,10.1.16.24,6,0x00,64,9212,49061,0x10,86,64,256
FLOW,10.1.11.1,1073741823,578,9c8e992433d0,001a4a16015a,0x0800,116,116,10.1.16.27,10.1.16.24,6,0x00,64,9212,49061,0x10,1522,1500,256
FLOW,10.1.11.1,574,573,001a4a744997,10604bb76125,0x0800,213,214,10.2.13.20,10.2.14.16,6,0x00,64,43427,6379,0x18,102,80,256
FLOW,10.1.11.1,0,574,10604bb76125,001a4a744957,0x0800,-1,213,10.2.14.22,10.2.13.14,6,0x08,63,3306,60584,0x18,85,63,256
FLOW,10.1.11.1,1073741823,563,001a4a744923,5475d0283adb,0x0800,55,55,10.50.5.12,95.222.186.156,6,0x00,64,443,50349,0x10,1442,1420,256
FLOW,10.1.11.1,574,592,001a4a744956,001a4a744955,0x0800,114,114,10.1.14.10,10.1.14.16,6,0x00,64,33660,6379,0x10,74,52,256
FLOW,10.1.11.1,1073741823,571,001a4a16015a,9c8e992433d0,0x0800,116,116,10.1.16.24,10.1.16.27,6,0x00,64,49061,9212,0x10,1522,1500,256
FLOW,10.1.11.1,573,592,001a4a744927,10604bb76125,0x0800,214,213,10.2.14.16,10.2.13.18,6,0x00,64,6379,55226,0x18,91,69,256
FLOW,10.1.11.1,0,573,10604bb76125,001a4a744927,0x0800,-1,214,10.2.13.18,10.2.14.16,6,0x00,63,55246,6379,0x18,136,114,256
FLOW,10.1.11.1,1073741823,571,001a4a160159,9c8e992433d0,0x0800,116,116,10.1.16.23,10.1.16.27,6,0x00,64,36732,9212,0x10,1522,1500,256
FLOW,10.1.11.1,0,578,10604bb76125,001a4a744917,0x0800,-1,117,10.1.14.15,10.1.17.11,6,0x00,63,27017,52746,0x10,1522,1500,256
FLOW,10.1.11.1,0,578,10604bb76125,001a4a744917,0x0800,-1,117,10.1.14.15,10.1.17.11,6,0x00,63,27017,52746,0x10,1522,1500,256
FLOW,10.1.11.1,0,579,10604bb76125,001a4a160167,0x0800,-1,114,10.1.12.200,10.1.14.25,6,0x00,63,52076,3306,0x10,74,52,256
FLOW,10.1.11.1,578,592,001a4a744917,10604bb76125,0x0800,117,114,10.1.17.11,10.1.14.15,6,0x00,64,52746,27017,0x10,74,52,256
FLOW,10.1.11.1,0,578,10604bb76125,001a4a744917,0x0800,-1,117,10.1.14.15,10.1.17.11,6,0x00,63,27017,54376,0x10,1522,1500,256
FLOW,10.1.11.1,0,578,10604bb76125,001a4a744917,0x0800,-1,117,10.1.14.15,10.1.17.11,6,0x00,63,27017,54148,0x10,1522,1500,256
FLOW,10.1.11.1,592,0,001a4a74499f,10604bb76125,0x0800,217,218,10.2.17.18,10.2.18.242,6,0x00,64,81,53503,0x10,1522,1500,256
FLOW,10.1.11.1,578,592,001a4a744917,10604bb76125,0x0800,117,114,10.1.17.11,10.1.14.15,6,0x00,64,54148,27017,0x10,74,52,256
FLOW,10.1.11.1,0,578,10604bb76125,001a4a744917,0x0800,-1,117,10.1.14.15,10.1.17.11,6,0x00,63,27017,54148,0x10,1522,1500,256
FLOW,10.1.11.1,0,578,10604bb76125,001a4a744917,0x0800,-1,117,10.1.14.15,10.1.17.11,6,0x00,63,27017,52810,0x10,1522,1500,256
FLOW,10.1.11.1,563,592,5475d0283adb,001a4a744923,0x0800,55,55,95.131.237.97,10.50.5.26,6,0x00,126,40211,443,0x14,64,42,256
FLOW,10.1.11.1,1073741823,563,001a4a744923,5475d0283adb,0x0800,55,55,10.50.5.12,109.192.45.63,6,0x00,64,443,49791,0x12,82,60,256
FLOW,10.1.11.1,0,574,10604bb76125,001a4a7449a1,0x0800,-1,217,10.2.18.242,10.2.17.17,6,0x00,63,58375,81,0x02,82,60,256
FLOW,10.1.11.1,563,592,5475d0283adb,001a4a744923,0x0800,55,55,173.245.53.118,10.50.5.14,6,0x28,55,17581,443,0x10,64,42,256
FLOW,10.1.11.1,0,573,10604bb76125,001a4a744927,0x0800,-1,214,10.2.13.19,10.2.14.16,6,0x00,63,43256,6379,0x18,138,116,256
FLOW,10.1.11.1,0,592,10604bb76125,001a4a744930,0x0800,-1,112,10.1.13.17,10.1.12.244,6,0x00,63,4444,49624,0x12,82,60,256
FLOW,10.1.11.1,0,574,10604bb76125,001a4a7449a1,0x0800,-1,217,10.2.14.18,10.2.17.17,6,0x00,63,27017,58646,0x10,1522,1500,256
FLOW,10.1.11.1,592,0,001a4a744930,10604bb76125,0x0800,112,113,10.1.12.220,10.1.13.22,6,0x00,64,5672,56594,0x18,95,73,256
FLOW,10.1.11.1,573,574,001a4a744927,10604bb76125,0x0800,214,213,10.2.14.16,10.2.13.20,6,0x00,64,6379,49407,0x18,84,62,256
FLOW,10.1.11.1,1073741823,592,5475d0283adb,001a4a744923,0x0800,55,55,162.158.222.24,10.50.5.22,6,0x00,57,26766,443,0x02,74,52,256
FLOW,10.1.11.1,0,578,10604bb76125,001a4a744917,0x0800,-1,117,10.1.14.15,10.1.17.11,6,0x00,63,27017,55742,0x10,1522,1500,256
FLOW,10.1.11.1,578,592,001a4a744917,10604bb76125,0x0800,117,214,10.1.17.11,10.2.14.15,6,0x00,64,39244,11213,0x10,74,52,256
`

this is making for me more difficult to understand, when I taked dump of infomation from sflowtool with options -g.
[dump.txt](https://github.com/sflow/sflowtool/files/539993/dump.txt)

I will try to use other software or wireshark to catch packet and check it deeply.

Thank You in advance for any suggestion.

**Comment by sflow** [comment]
1073741823 (0x3FFFFFFF) has a special meaning in sFlow v5.  It means "internal port".   So if the inputPort field is 1073741823 that just means the sampled packet came from the management CPU on the switch.   So you'll see that appear on things like spanning-tree packets or routing updates.  That is valid sFlow.

A VLAN value of -1 means "unknown" -- in the same was as outputPort==0 means "unknown".   The sFlow standard allows for there to be some gaps in the non-essential fields like this because sometimes the architecture of the device makes it very hard to fill them in for all cases,  and sFlow was designed to be easy to implement in the real world.   While it is very helpful to always know the egress port for unicast traffic,   it is not always required.  Especially if you follow the recommendations and run sFlow on every port of every switch (and on every server and hypervisor too - see http://sflow.net for freeware agents).   If the egress port is missing your sFlow collector can still trace the traffic path because it will show up as ingress traffic at the other end of the link.

So if HP looks at it they may find that they can make a routing lookup and fill in the egress port after all,  however I don't think it can be called a bug.

Neil

P.S.  There are other things the sFlow standard is very strict about,  such as that the sampling must be random packet-count-based sampling,  the interface counters must be sent periodically and the XDR formatting must be correct.  If that is not happening then it's not sFlow,  you can't call it sFlow,  etc. etc.
